<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class ProductTableSeeder extends Seeder
{
    public function run()
    {
        $uuidManager = UuidManager::getInstance();
        $faker = Faker::create();

        DB::table('products')->insert([
            [
                'id' => $uuidManager->generate('samsung-galaxy-s21'),
                'name' => 'Samsung Galaxy S21',
                'price' => 12999999,
                'sku' => 'SAMSUNG-GALAXY-S21',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('samsung'),
                'category_id' => $uuidManager->get('smartphone'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('apple-iphone-12-pro-max'),
                'name' => 'Apple iPhone 12 Pro Max',
                'price' => 19999999,
                'sku' => 'APPLE-IPHONE-12-PRO-MAX',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('apple'),
                'category_id' => $uuidManager->get('smartphone'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('xiaomi-redmi-note-10-pro'),
                'name' => 'Xiaomi Redmi Note 10 Pro',
                'price' => 4999999,
                'sku' => 'XIAOMI-REDMI-NOTE-10-PRO',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('xiaomi'),
                'category_id' => $uuidManager->get('smartphone'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('samsung-galaxy-tab-s7'),
                'name' => 'Samsung Galaxy Tab S7',
                'price' => 12999999,
                'sku' => 'SAMSUNG-GALAXY-TAB-S7',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('samsung'),
                'category_id' => $uuidManager->get('tablet'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('apple-ipad-pro-2021'),
                'name' => 'Apple iPad Pro 2021',
                'price' => 19999999,
                'sku' => 'APPLE-IPAD-PRO-2021',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('apple'),
                'category_id' => $uuidManager->get('tablet'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('xiaomi-mi-pad-5'),
                'name' => 'Xiaomi Mi Pad 5',
                'price' => 4999999,
                'sku' => 'XIAOMI-MI-PAD-5',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('xiaomi'),
                'category_id' => $uuidManager->get('tablet'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('samsung-galaxy-book-s'),
                'name' => 'Samsung Galaxy Book S',
                'price' => 12999999,
                'sku' => 'SAMSUNG-GALAXY-BOOK-S',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('samsung'),
                'category_id' => $uuidManager->get('laptop'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('apple-macbook-air-2021'),
                'name' => 'Apple MacBook Air 2021',
                'price' => 19999999,
                'sku' => 'APPLE-MACBOOK-AIR-2021',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('apple'),
                'category_id' => $uuidManager->get('laptop'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('xiaomi-redmi-book-pro'),
                'name' => 'Xiaomi Redmi Book Pro',
                'price' => 4999999,
                'sku' => 'XIAOMI-REDMI-BOOK-PRO',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('xiaomi'),
                'category_id' => $uuidManager->get('laptop'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('samsung-odyssey-g9'),
                'name' => 'Samsung Odyssey G9',
                'price' => 12999999,
                'sku' => 'SAMSUNG-ODYSSEY-G9',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('samsung'),
                'category_id' => $uuidManager->get('desktop'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
            [
                'id' => $uuidManager->generate('apple-imac-2021'),
                'name' => 'Apple iMac 2021',
                'price' => 19999999,
                'sku' => 'APPLE-IMAC-2021',
                'description' => $faker->paragraph,
                'stock_quantity' => 10,
                'image' => '/default/product.png',
                'manufacturer_id' => $uuidManager->get('apple'),
                'category_id' => $uuidManager->get('desktop'),
                'created_at' => now(),
                'created_by' => $uuidManager->get('admin'),
            ],
        ]);
    }
}
